apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-ide-k8s-controller
    app.kubernetes.io/part-of: cloud-ide-k8s-controller
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
