apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv4
spec:
  nfs: # 存储类型，和底层正则的存储对应
    path: /data/nfs/pv4
    server: 192.168.44.100
  capacity: # 存储能力，目前只支持存储空间的设置
    storage: 5Gi
  accessModes: # 访问模式
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle # 回收策略

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5
spec:
  nfs: # 存储类型吗，和底层正则的存储对应
    path: /data/nfs/pv5
    server: 192.168.44.100
  capacity: # 存储能力，目前只支持存储空间的设置
    storage: 4Gi
  accessModes: # 访问模式
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle # 回收策略
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv6
spec:
  nfs: # 存储类型吗，和底层正则的存储对应
    path: /data/nfs/pv6
    server: 192.168.44.100
  capacity: # 存储能力，目前只支持存储空间的设置
    storage: 5Gi
  accessModes: # 访问模式
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle # 回收策略
